### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by jk00789** [stroyan/led-drv-f4-220#5]
```
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-0.deb11.7-amd64'
  LD [M]  /root/led-drv-f4-220/leds-f4-220.ko
  BTF [M] /root/led-drv-f4-220/leds-f4-220.ko
/bin/sh: 1: ./tools/bpf/resolve_btfids/resolve_btfids: not found
make[2]: *** [/usr/src/linux-headers-6.1.0-0.deb11.7-common/scripts/Makefile.modfinal:63: /root/led-drv-f4-220/leds-f4-220.ko] Error 127
make[2]: *** Deleting file '/root/led-drv-f4-220/leds-f4-220.ko'
make[1]: *** [/usr/src/linux-headers-6.1.0-0.deb11.7-common/Makefile:1954: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-0.deb11.7-amd64'
make: *** [Makefile:10: default] Error 2
```
Any suggestions for successful compile?

**Comment by stroyan** [comment]
That error is related to trying to build with data for BPF, (Berkeley Packet Filter), and not finding the related tools in the kernel build.  I have not run into that building the driver myself.  I am currently using linux-headers-5.19.0-50-generic from Ubuntu 22.04.2 which does have a resolve_btfids executable in linux-headers-5.19.0-50-generic .  But I don't think the led-drv-f4-220 driver has any preference to how that is configured.

There is a related debian bug- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027306
That includes a patch for the debian linux-kbuild-6.0 package that builds the missing resolve_btfids executable.
