### ISSUE TITLE
How to compile in DSM 6.1.7

### ISSUE THREAD

**Issue by xqlee-official** [stroyan/led-drv-f4-220#6]
How to compile in DSM 6.1.7。I have installed gcc and make components via ipkg ，but make error

**Comment by stroyan** [comment]
I have only compiled this on Ubuntu using dkms.  It would be quite a project to port this to a Synology kernel and build tools.
The oldest version of the kernel I see at "Synology Open Source Project", https://sourceforge.net/projects/dsgpl/ is 6.2.4-25556 .
So even finding the source code for DSM 6.1.7 kernels may be a challenge.
